# Generated by Django 3.2.6 on 2021-08-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperPoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poder', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'SuperPoderes',
            },
        ),
        migrations.CreateModel(
            name='SuperHeroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hero', models.CharField(blank=True, max_length=150, null=True)),
                ('name_secret', models.CharField(blank=True, max_length=150, null=True)),
                ('super_poder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heros.superpoder')),
            ],
            options={
                'verbose_name_plural': 'SuperHeroes',
            },
        ),
    ]
